# Based on https://github.com/nanoninja/docker-nginx-php-mysql

version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "3000:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ./web:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template
      - ./docker/ssl:/etc/ssl
    restart: always
    depends_on:
      - php
      - mysqldb

  php:
    build:
      context: docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    env_file: .env
    restart: always
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
      - ./web:/var/www/html

#  composer:
#    image: "composer"
#    volumes:
#      - "./web/app:/app"
#    command: install

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    depends_on:
      - mysqldb

  mysqldb:
    platform: linux/x86_64
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    ports:
      - "8989:3306"
    volumes:
      - ./docker/mysql:/etc/mysql
      - ./data/db/mysql:/var/lib/mysql
      - ./data/db/mysql-files:/var/lib/mysql-files
      - ./logs/mysql:/var/logs/mysql
      # В описании докера написано, что, если в локальую папку, которая мапится на /docker-entrypoint-initdb.d, положить sql или bash файлы, то они будут выполнены после разворачивания mysql.
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
